[theme]
primaryColor = "#E64980"
backgroundColor = "#FFF5FD" 
secondaryBackgroundColor = "#FCE7EC"
textColor = "#31394D"
linkColor = "#A23963"
# headingFont = "Roboto"

[browser]
gatherUsageStats = true

[client]
showErrorDetails = "none"

[[theme.fontFaces]]
family = "Roboto"
url = "https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
weight = 400
style = "normal"
