[theme]
primaryColor = "#E64980"
backgroundColor = "#FFF5FD" 
secondaryBackgroundColor = "#FCE7EC"
textColor = "#31394D"
linkColor = "#A23963"
# headingFont = "Roboto"

[browser]
gatherUsageStats = true

[client]
showErrorDetails = "none"

[secrets]
files = ["/Users/alejo/Code/orcid2taxid/.env"]